# scripts/constants.py

COMMON_SKILLS = [
    "python",
    "java",
    "c++",
    "javascript",
    "sql",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "tensorflow",
    "keras",
    "scikit-learn",
    "openCV",
    "nltk",
    "beautifulsoup",
    "selenium",
    "git",
    "github",
    "vscode",
    "jupyter",
    "streamlit",
    "supabase",
    "tableau",
    "power bi",
    "excel",
    "data analysis",
    "machine learning",
    "deep learning",
    "nlp",
    "problem-solving",
    "communication",
    "teamwork",
]

EDUCATION_KEYWORDS = [
    "b.tech",
    "bachelor",
    "bachelor's",
    "be",
    "bs",
    "m.tech",
    "master",
    "master's",
    "ms",
    "msc",
    "phd",
    "diploma",
    "degree",
    "engineering",
    "computer science",
    "electronics",
    "electrical",
    "statistics",
    "mathematics",
    "data science",
]

SECTION_HEADERS = [
    "experience",
    "projects",
    "education",
    "skills",
    "certifications",
    "awards",
    "publications",
    "honors",
]

JOB_ROLES = [
    "data analyst",
    "data scientist",
    "machine learning engineer",
    "software engineer",
    "backend developer",
    "frontend developer",
    "full stack developer",
    "business analyst",
    "research intern",
]

TOOL_SYNONYMS = {
    "power bi": ["powerbi"],
    "excel": ["microsoft excel"],
    "tensorflow": ["tf"],
    "scikit-learn": ["sklearn"],
    "vscode": ["visual studio code"],
    "github": ["git"],
    "jupyter": ["jupyter notebooks", "jupyter notebook"],
}

ACTION_VERBS = [
    "developed",
    "built",
    "implemented",
    "created",
    "designed",
    "deployed",
    "analyzed",
    "automated",
    "streamlined",
    "improved",
    "led",
    "collaborated",
    "researched",
    "tested",
    "trained",
    "monitored",
    "visualized",
]
