# General skills list covering multiple domains
GENERAL_SKILLS = {
    "programming_languages": [
        "python",
        "java",
        "c++",
        "javascript",
        "ruby",
        "swift",
        "go",
        "perl",
        "rust",
        "kotlin",
        "scala",
        "typescript",
        "php",
        "r",
        "matlab",
        "c#",
        "sql",
        "shell scripting",
        "bash",
        "html",
        "css",
    ],
    "data_science": [
        "data analysis",
        "machine learning",
        "deep learning",
        "artificial intelligence",
        "natural language processing",
        "nlp",
        "data mining",
        "statistical modeling",
        "feature engineering",
        "predictive modeling",
        "time series analysis",
        "regression analysis",
        "classification",
        "clustering",
        "anomaly detection",
        "reinforcement learning",
    ],
    "data_tools": [
        "pandas",
        "numpy",
        "matplotlib",
        "seaborn",
        "scikit-learn",
        "tensorflow",
        "keras",
        "pytorch",
        "xgboost",
        "flask",
        "streamlit",
        "hadoop",
        "spark",
        "tableau",
        "power bi",
        "sql",
        "aws",
        "gcp",
        "azure",
        "docker",
        "git",
        "github",
        "gitlab",
    ],
    "web_development": [
        "html",
        "css",
        "javascript",
        "react",
        "angular",
        "vue",
        "node.js",
        "express",
        "django",
        "flask",
        "jquery",
        "webpack",
        "sass",
        "bootstrap",
        "tailwind",
        "graphql",
        "api",
        "restful services",
        "microservices",
        "mongodb",
        "postgresql",
    ],
    "cloud_technologies": [
        "aws",
        "azure",
        "gcp",
        "docker",
        "kubernetes",
        "terraform",
        "ci/cd",
        "devops",
        "jenkins",
        "ansible",
        "cloudformation",
    ],
    "business_analysis": [
        "business analysis",
        "business intelligence",
        "requirement gathering",
        "data visualization",
        "process mapping",
        "project management",
        "agile",
        "scrum",
        "kanban",
        "stakeholder management",
        "budgeting",
        "risk management",
        "change management",
    ],
    "marketing": [
        "digital marketing",
        "seo",
        "sem",
        "email marketing",
        "social media marketing",
        "content marketing",
        "google analytics",
        "conversion optimization",
        "affiliate marketing",
        "market research",
        "growth hacking",
        "marketing automation",
        "adwords",
    ],
    "database_management": [
        "mysql",
        "postgresql",
        "oracle",
        "mongodb",
        "cassandra",
        "redis",
        "sql server",
        "database design",
        "database administration",
        "data warehousing",
        "etl",
        "nosql",
        "big data",
        "database optimization",
    ],
    "software_engineering": [
        "agile development",
        "version control",
        "unit testing",
        "functional programming",
        "object-oriented programming",
        "design patterns",
        "software architecture",
        "microservices",
        "api design",
        "continuous integration",
        "software debugging",
        "object-oriented design",
        "software testing",
        "debugging",
        "refactoring",
        "performance optimization",
    ],
    "soft_skills": [
        "communication",
        "teamwork",
        "leadership",
        "problem solving",
        "critical thinking",
        "time management",
        "negotiation",
        "adaptability",
        "conflict resolution",
        "empathy",
        "collaboration",
        "presentation skills",
        "decision making",
        "creativity",
    ],
}

# Keywords for educational qualifications
EDUCATION_KEYWORDS = [
    "bachelor",
    "master",
    "doctorate",
    "phd",
    "engineering",
    "computer science",
    "data science",
    "electrical",
    "mathematics",
    "economics",
    "business",
    "mba",
    "information technology",
    "statistics",
    "finance",
    "marketing",
    "physics",
    "chemistry",
    "biology",
    "healthcare",
    "medicine",
    "law",
]

# Job roles
JOB_ROLES = [
    "data scientist",
    "software engineer",
    "data analyst",
    "business analyst",
    "web developer",
    "full-stack developer",
    "frontend developer",
    "backend developer",
    "machine learning engineer",
    "data engineer",
    "marketing manager",
    "project manager",
    "product manager",
    "system administrator",
    "devops engineer",
    "cloud engineer",
    "ux/ui designer",
    "seo specialist",
    "business intelligence analyst",
    "research scientist",
    "content writer",
    "marketing strategist",
    "graphic designer",
    "data architect",
]

# Synonyms for tools and technologies (e.g., versions, alternate names)
TOOL_SYNONYMS = {
    "python": ["py", "python3", "py3"],
    "javascript": ["js", "es6"],
    "java": ["j2ee", "jdk"],
    "sql": ["postgresql", "mysql", "mssql", "sqlite", "no-sql"],
    "tensorflow": ["tf", "keras"],
    "aws": ["amazon web services", "amazon cloud"],
    "docker": ["containerization", "docker container"],
    "git": ["github", "gitlab", "bitbucket"],
    "html": ["hypertext markup language"],
    "css": ["cascading style sheets"],
}

# Experience-based regex to match experience (years)
EXPERIENCE_REGEX = r"\b(\d+)\s*years?\b|\b(\d+\.\d+)\s*years?\b"
